### ISSUE TITLE
3 funkcja

### ISSUE THREAD

**Issue by Shaveek23** [korona-science/homework-Shaveek23#1]
W 3 funkcji chodzi o zwrócenie liczby 'Country/Region', gdzie danego dnia liczba zarażeń nie zmieniła się w porównaniu do dnia poprzedniego. Dlaczego więc rozwiązanie nie przewiduje grupowania po 'Province/State' skoro np. dla Chin istnieje wiele prowincji i wzrost zarażonych chociaż w jednej prowincji już dyskwalifikuje ten kraj, w testach jednak chodzi o liczenie prowincji nie krajów...

**Comment by RouNNdeL** [comment]
Jest to błąd w treści, sorry
